//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace autocomplete.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StyliList
    {
        public int ID { get; set; }
        public string PartNo { get; set; }
        public string TipType { get; set; }
        public string TipSize { get; set; }
        public string TipAngle { get; set; }
        public string TipMaterial { get; set; }
        public string StylusType { get; set; }
        public string ShankClearance { get; set; }
        public string EffectiveLength { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string Delivery { get; set; }
        public string Image { get; set; }
        public string Description { get; set; }
        public string InstrumentType { get; set; }
        public string ShankLength { get; set; }
        public string DataType { get; set; }
        public string DisplayPrice { get; set; }
        public Nullable<decimal> PrimeCost { get; set; }
        public string FldRndSur { get; set; }
        public string FldInstrumentGauge { get; set; }
        public string FldDocPath { get; set; }
        public Nullable<double> LastPTValue1 { get; set; }
        public Nullable<double> LastPTValue2 { get; set; }
        public Nullable<double> FlickError1 { get; set; }
        public Nullable<double> FlickError2 { get; set; }
        public Nullable<double> GaugeRange { get; set; }
    }
}
